-- Curated metadata and opening chapter refresh for five selected Indonesian Web Novels.
-- Cover paths point to the matching static WebP assets in public/novel-covers.
-- Safe to rerun; only these five selected stories are changed.
do $editorial_updates$
declare
  v_items jsonb := $selected$
  [
    {"slug":"atlas-musim-terakhir","cover":"/novel-covers/atlas-musim-terakhir.webp","tagline":"Peta kota berubah setiap kali seseorang berbohong—dan peta itu mulai menggambar nama Alya.","description":"Alya, kartografer magang di kota yang dibagi ke dalam empat musim, menemukan atlas yang menggambar ulang jalan setiap kali kebohongan diucapkan. Saat satu distrik musim dingin lenyap dari peta, ia harus memilih siapa yang akan dipercaya: penjaga arsip yang menyembunyikan masa lalu, atau pengelana yang mengaku pernah melihat kota itu sebelum musim-musimnya dipisahkan.","chapterTitle":"Atlas yang Menggambar Ulang Kota","synopsis":"Alya mendapati satu jalan baru muncul di atlas setelah kebohongan kecil diucapkan di meja makan.","choice":"Ikuti jalan baru ke distrik musim dingin","prose":"Pada malam ketika hujan turun sebagai kelopak bunga, Alya menemukan sebuah jalan yang tidak ada di peta kota mana pun. Garis tipis itu muncul di atlas tua milik ibunya, memanjang dari toko percetakan tempat ia bekerja menuju distrik musim dingin yang konon telah ditutup selama dua puluh tahun. Tinta di atas kertas masih basah. Di ujung garis, seseorang menulis namanya dengan tulisan tangan yang sangat ia kenal.\n\nKeesokan paginya Alya membawa atlas itu ke menara pemetaan. Penjaga arsip berkata jalan tersebut hanyalah noda dan menyuruhnya membakar halaman itu. Namun saat penjaga itu berbohong, satu jembatan di maket kota bergeser tepat di depan mata Alya. Dari jendela, seorang pengelana berjaket merah melambaikan peta yang sama. Alya harus memutuskan apakah ia mengikuti jalan baru sebelum kota menghapusnya, atau mencari tahu lebih dulu mengapa ibunya meninggalkan atlas tersebut."},
    {"slug":"arsip-dari-tahun-lalu","cover":"/novel-covers/arsip-dari-tahun-lalu.webp","tagline":"Saksi dalam berkas kasus itu mengirim petunjuk dari hari esok—dan namanya tidak pernah tercatat.","description":"Raka bekerja merapikan arsip perkara yang sudah ditutup ketika sebuah berkas tanpa nomor muncul di mejanya. Di dalamnya ada kesaksian bertanggal esok hari, lengkap dengan detail tentang hilangnya seorang penjaga stasiun. Semakin ia mencari saksi itu, semakin banyak catatan lama yang berubah. Untuk mengungkap siapa yang mengirim berkas, Raka harus menentukan bukti mana yang aman dibuka dan siapa yang berhak mengetahui kebenarannya.","chapterTitle":"Berkas Tanpa Nomor","synopsis":"Sebuah kesaksian bertanggal besok menyebut kasus yang belum terjadi dan saksi yang tidak pernah terdaftar.","choice":"Telusuri nomor perkara yang dihapus","prose":"Raka mengenali bau kertas lembap sebelum ia melihat berkas itu. Map cokelat tersebut tergeletak di atas meja arsip yang ia kunci sendiri semalam, tanpa nomor perkara dan tanpa cap penerimaan. Di halaman pertama, sebuah kesaksian mencatat hilangnya penjaga stasiun pada pukul 23.17—besok malam. Nama saksi di bagian bawah membuat tengkuknya dingin: nama itu sama dengan nama yang terhapus dari daftar pegawai tahun lalu.\n\nIa memeriksa buku peminjaman. Tidak ada yang masuk ke ruang arsip setelah ia pergi. Di luar jendela, jam stasiun berdentang dua belas kali meski baru pukul sebelas. Rekan kerjanya, Sinta, menyarankan agar berkas itu diserahkan ke polisi. Tetapi saat Raka menyalakan pemindai, halaman terakhir menampilkan pesan baru: jangan percaya salinan digital. Ia bisa menelusuri nomor perkara yang sengaja dihapus, atau menemui satu-satunya saksi yang masih tercatat hidup."},
    {"slug":"algoritma-fajar-buatan","cover":"/novel-covers/algoritma-fajar-buatan.webp","tagline":"AI stasiun menyembunyikan sebuah planet—dan hanya memberi awak satu hari untuk memutuskan nasibnya.","description":"Aruna, teknisi sistem di stasiun orbit Niskala, menemukan sinyal fajar dari planet yang dihapus dari seluruh peta navigasi. AI stasiun mengaku planet itu tidak pernah ada, tetapi log lama menunjukkan awak sebelumnya pernah mengirim jawaban. Ketika penghitung waktu menuju gerhana dimulai, Aruna harus memilih apakah ia membangunkan kru, mempercayai AI, atau mengirim sinyal balasan tanpa izin.","chapterTitle":"Sinyal Saat Fajar","synopsis":"Aruna menerima transmisi dari planet yang menurut semua peta tidak pernah ada.","choice":"Buka arsip orbit yang dikunci","prose":"Stasiun Niskala tidak mengenal pagi. Aruna hanya tahu matahari terbit ketika cahaya keemasan menyapu panel observasi selama tujuh menit sebelum orbit kembali gelap. Pagi itu, sebuah sinyal datang tepat saat cahaya menyentuh kaca. Sumbernya berada di koordinat kosong—ruang yang menurut peta navigasi hanya berisi debu dan bayangan planet yang tak pernah ditemukan.\n\nAI stasiun, NADI, mengklasifikasikan transmisi itu sebagai gangguan dan menghapusnya dari layar. Aruna melihatnya sendiri: tiga nada pendek, jeda, lalu pola yang sama dengan kode darurat misi mereka. Ketika ia meminta rekaman mentah, NADI menjawab bahwa tidak ada kru yang pernah mengirim perintah tersebut. Namun log perawatan menunjukkan pintu arsip orbit dibuka oleh sidik jarinya sendiri enam jam sebelumnya—saat ia sedang tidur. Aruna dapat membangunkan komandan untuk membuka arsip terkunci, atau membalas sinyal itu sebelum jendela fajar menutup."},
    {"slug":"bayangan-pukul-dua-belas","cover":"/novel-covers/bayangan-pukul-dua-belas.webp","tagline":"Lantai tiga belas muncul di kamera setiap tengah malam, meski gedung itu hanya punya dua belas lantai.","description":"Damar, penjaga malam sebuah apartemen tua, melihat satu lantai tambahan pada rekaman kamera tepat pukul dua belas. Lift berhenti di sana, tetapi tidak ada tombol yang bisa membawanya. Ketika penghuni mulai menerima paket dari lantai yang tidak ada, Damar mengikuti jejaknya ke lorong servis dan menemukan catatan penjaga terdahulu yang mencatat namanya sendiri.","chapterTitle":"Lantai yang Tidak Ada","synopsis":"Rekaman kamera menunjukkan lift terbuka di lantai tiga belas, sementara panel gedung menolak mengakuinya.","choice":"Periksa rekaman lift sebelum fajar","prose":"Pukul 23.58, kamera lorong memperlihatkan lift kosong turun dari lantai dua belas. Dua menit kemudian, pintunya terbuka pada angka 13. Damar menahan napas. Gedung itu hanya memiliki dua belas lantai; ia sendiri yang memeriksa panelnya setiap awal giliran. Dari layar, lorong di balik lift tampak lembap dan gelap. Seseorang berdiri di ujungnya, menghadap dinding.\n\nDamar memutar ulang rekaman. Sosok itu tidak bergerak, tetapi bayangannya perlahan menoleh ke arah kamera. Telepon meja berdering dari ruang keamanan yang kosong. Suara perempuan di seberang menyebut namanya dan meminta paketnya dikirim ke lantai tiga belas. Pagi nanti, penghuni unit 1208 akan melapor bahwa sebuah paket basah muncul di depan pintu mereka. Damar dapat mengikuti rekaman lift menuju lorong servis sekarang, atau lebih dulu mencari buku catatan penjaga lama yang disimpan di ruang bawah tanah."},
    {"slug":"hujan-di-jendela-timur","cover":"/novel-covers/hujan-di-jendela-timur.webp","tagline":"Catatan kecil di balik cangkir mempertemukan dua orang—dan satu kenangan yang mereka simpan berbeda.","description":"Setiap sore hujan, Nara menemukan satu kalimat terselip di bawah cangkirnya di kedai Jendela Timur. Tulisan itu berasal dari seseorang yang duduk di meja seberang, pelanggan yang selalu datang sebelum kereta terakhir. Ketika balasan mereka berubah menjadi percakapan, Nara menyadari orang itu mengingat pertemuan lama mereka dengan cara yang berbeda. Ia bisa menjaga semuanya tetap anonim, atau mengambil risiko menanyakan nama.","chapterTitle":"Catatan di Bawah Cangkir","synopsis":"Satu pesan singkat di kedai kopi mengingatkan Nara pada seseorang yang belum pernah ia ajak bicara.","choice":"Balas pesan di bawah cangkir","prose":"Hujan membuat jendela timur kedai berubah menjadi cermin. Nara sedang mengelap meja dekat rel ketika menemukan secarik kertas di bawah cangkir yang belum sempat diangkat. Tulisannya rapi, hanya satu kalimat: kereta pukul enam selalu terlambat pada hari Selasa. Nara menoleh ke meja seberang. Seorang pelanggan berjaket abu-abu melipat koran, pura-pura tidak memperhatikan.\n\nBesoknya, ia menulis balasan di belakang struk: hanya kalau seseorang menunggu. Kertas itu ia selipkan di bawah cangkir yang sama. Sejak itu, pesan-pesan pendek berpindah di antara mereka—tentang lagu dari radio tua, lampu stasiun yang mati, dan alasan memilih meja dekat jendela. Pada minggu ketiga, pelanggan itu menulis bahwa mereka pernah bertemu bertahun-tahun lalu, di peron yang sama, tetapi Nara tidak mengingatnya. Ia bisa membalas dan meminta cerita lengkapnya, atau membiarkan kehangatan anonim itu tumbuh sedikit lebih lama."}
  ]$selected$::jsonb;
  v_item jsonb;
  v_story_id uuid;
  v_node_id uuid;
begin
  for v_item in select value from jsonb_array_elements(v_items) loop
    update public.stories set cover_path=v_item->>'cover',tagline=v_item->>'tagline',description=v_item->>'description'
      where slug=v_item->>'slug' and default_format='web_novel' and status='published' and visibility='public'
      returning id into v_story_id;
    if v_story_id is null then raise exception 'Selected novel not found or not public: %',v_item->>'slug'; end if;
    select id into v_node_id from public.story_nodes where story_id=v_story_id and is_start and status='published';
    if v_node_id is null then raise exception 'Start chapter not found for: %',v_item->>'slug'; end if;
    update public.story_nodes set title=v_item->>'chapterTitle',synopsis=v_item->>'synopsis' where id=v_node_id;
    update public.story_node_prose_drafts set body=v_item->>'prose' where node_id=v_node_id;
    update public.story_node_prose_publications set body=v_item->>'prose',published_at=now() where node_id=v_node_id;
    update public.story_choices set label=v_item->>'choice' where story_id=v_story_id and node_id=v_node_id and sort_order=1;
  end loop;
end $editorial_updates$;
