"use client";
import { useState } from "react";
import { Trophy, Compass, GitBranch, BookOpen, Crown } from "lucide-react";
import { PageHeading, ProgressBar } from "./design-ui";
export default function Achievements({ discovered, completed, started }: { discovered: number; completed: number; started: number }) {
  const [filter, setFilter] = useState("all");
  const badges = [{ title: "Langkah pertama", description: "Mulai satu cerita", current: started, target: 1, category: "explore", icon: Compass }, { title: "Penjelajah jalur", description: "Jelajahi 10 bab dalam perjalanan aktif", current: discovered, target: 10, category: "explore", icon: GitBranch }, { title: "Satu takdir", description: "Selesaikan satu cerita", current: completed, target: 1, category: "endings", icon: Crown }, { title: "Kutu buku", description: "Jelajahi 100 bab dalam perjalanan aktif", current: discovered, target: 100, category: "reading", icon: BookOpen }];
  const earned = badges.filter(b => b.current >= b.target).length;
  return <main className="px-page"><PageHeading title="Pencapaian" back="/profile" /><div className="px-content"><section className="px-achievement-summary"><span><Trophy size={28} strokeWidth={1.2} /></span><div><h2>Koleksi penjelajah</h2><p>{earned} dari {badges.length} lencana diraih</p><ProgressBar value={earned / badges.length * 100} label="Lencana diraih" /></div></section><div className="px-chips">{[["all", "Semua"], ["explore", "Jelajah"], ["reading", "Membaca"], ["endings", "Akhir"]].map(([id, label]) => <button key={id} aria-pressed={filter === id} onClick={() => setFilter(id)}>{label}</button>)}</div><h2 className="px-subtitle">Perjalanan pencapaian</h2><div className="px-achievement-list">{badges.filter(b => filter === "all" || b.category === filter).map(({ title, description, current, target, icon: Icon }) => <article key={title}><span className="px-medallion"><Icon size={28} strokeWidth={1.2} /></span><div><h3>{title}</h3><p>{description}</p><ProgressBar value={Math.min(100, current / target * 100)} label={title} /><small className={current >= target ? "px-success" : ""}>{current >= target ? "Tercapai" : `${current} / ${target}`}</small></div></article>)}</div><p className="px-footnote">Teruslah membaca untuk membuka kemungkinan baru. Progres mengikuti perjalanan aktifmu.</p></div></main>;
}
