"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { Search, BookOpen } from "lucide-react";
import type { Story } from "@/lib/data";
import { Cover, PageHeading, ProgressBar } from "./design-ui";
import { readSavedStories } from "./saved-stories";
export type LibraryEntry = { storyId: string; nodeKey?: string; chapter?: string; completed: boolean; discovered: number; total: number; endings: number; totalEndings: number };
export default function LibraryView({ stories, entries, accountKey }: { stories: Story[]; entries: LibraryEntry[]; accountKey: string }) {
  const [tab, setTab] = useState("reading"); const [query, setQuery] = useState(""); const [saved, setSaved] = useState<string[]>([]); const [sort, setSort] = useState("recent");
  useEffect(() => { const update = () => setSaved(readSavedStories(accountKey)); update(); window.addEventListener("storage", update); window.addEventListener("pixinia:saved", update); return () => { window.removeEventListener("storage", update); window.removeEventListener("pixinia:saved", update); }; }, [accountKey]);
  const listed = (tab === "saved" ? stories.filter(story => saved.includes(story.id)) : entries.filter(entry => tab === "completed" ? entry.completed : !entry.completed).map(entry => stories.find(story => story.id === entry.storyId)).filter((story): story is Story => !!story)).filter(story => story.title.toLocaleLowerCase("id-ID").includes(query.toLocaleLowerCase("id-ID")));
  if (sort === "title") listed.sort((a, b) => a.title.localeCompare(b.title, "id"));
  return <main className="px-page"><PageHeading title="Pustaka kamu" /><div className="px-content"><div className="px-segmented" role="group" aria-label="Kategori pustaka">{[["reading", "Dibaca"], ["completed", "Selesai"], ["saved", "Disimpan"]].map(([value, label]) => <button key={value} aria-pressed={tab === value} onClick={() => setTab(value)}>{label}</button>)}</div><label className="px-search"><Search size={16} /><input type="search" aria-label="Cari di pustaka" placeholder="Cari di pustakamu…" value={query} onChange={event => setQuery(event.target.value)} /></label><div className="px-list-meta"><span>{listed.length} cerita</span><select aria-label="Urutan pustaka" value={sort} onChange={event => setSort(event.target.value)}><option value="recent">Terakhir dibaca</option><option value="title">Judul A–Z</option></select></div>
    <div className="px-library-list">{listed.map(story => { const entry = entries.find(item => item.storyId === story.id); const percent = entry?.total ? Math.min(100, entry.discovered / entry.total * 100) : 0; return <article className="px-continue" key={story.id}><Link href={`/stories/${story.slug}`}><Cover path={story.cover_path} title={story.title} /></Link><div><Link href={`/stories/${story.slug}`}><h2>{story.title}</h2></Link><p className="px-gold">{entry?.chapter || "Siap untuk dibaca"}</p><ProgressBar value={percent} label={`Penjelajahan ${story.title}`} /><div className="px-progress-labels"><span>{Math.round(percent)}% dijelajahi</span><span>{entry?.endings ?? 0}/{entry?.totalEndings ?? 0} akhir</span></div><Link className="px-soft-button" href={entry?.nodeKey ? `/read/${story.slug}/${entry.nodeKey}` : `/stories/${story.slug}`}>{entry?.completed ? "Baca lagi" : "Lanjut membaca"}</Link></div></article>; })}</div>
    {!listed.length && <div className="empty-state"><BookOpen size={28} /><h2>{query ? "Cerita tidak ditemukan" : "Petualanganmu menunggu"}</h2><p>{tab === "saved" ? "Simpan cerita dari halaman detail untuk menemukannya di sini." : "Mulai membaca dan perjalananmu akan muncul di sini."}</p><Link className="px-button" href="/explore">Jelajahi cerita</Link></div>}{tab === "saved" && <p className="px-footnote">Cerita yang disimpan tersedia di browser ini.</p>}
  </div></main>;
}
